version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./logs:/app/logs
    depends_on:
      - migrations

  migrations:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: ["sh", "-c", "pip install -r requirements.txt && alembic upgrade head"]

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      api:
        condition: service_healthy
