services:
  backend:
    build: .
    container_name: soznai-backend
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./soznai.db}
      BOT_TOKEN: ${BOT_TOKEN:-}
      WEBAPP_URL: ${WEBAPP_URL:-http://localhost:8000/webhook}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET:-dev-secret}
      VERSION: ${VERSION:-0.1.0}
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    command: >
      bash -lc "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db

  frontend:
    image: python:3.11-slim
    container_name: soznai-frontend
    working_dir: /frontend
    command: python -m http.server 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend:ro

  db:
    image: postgres:15
    container_name: soznai-db
    environment:
      POSTGRES_USER: soznai
      POSTGRES_PASSWORD: soznai
      POSTGRES_DB: soznai
    ports:
      - "5432:5432"
    volumes:
      - soznai_data:/var/lib/postgresql/data

volumes:
  soznai_data:
