[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
    "backend/alembic",
    "node_modules",
]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "ASYNC", "RUF"]
ignore = ["E203", "B008"]

[tool.coverage.run]
branch = true
source = ["backend"]

[tool.coverage.report]
fail_under = 85
show_missing = true
skip_covered = true

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_configs = true
packages = ["backend"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["W391"]
exclude = ["backend/alembic", "node_modules"]
